name: hyper_storage_monorepo

publish_to: none

environment:
  sdk: ^3.9.0

workspace:
  - packages/hyper_storage
  - packages/hyper_storage_hive
  - packages/hyper_storage_shared_preferences
  - packages/hyper_secure_storage