include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    use_super_parameters: true
    prefer_relative_imports: true
    public_member_api_docs: true

formatter:
  page_width: 120
  trailing_commas: preserve
