name: hyper_storage_flutter
description: A package that makes it easy to use hyper_storage in Flutter applications.

version: 0.1.0

repository: https://github.com/hyper-designed/hyper_storage
homepage: https://github.com/hyper-designed/hyper_storage/tree/main/packages/hyper_storage_flutter

environment:
  sdk: ^3.9.0
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  hyper_storage: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  coverage: ^1.15.0

topics:
  - flutter
  - storage
  - reactive
  - valuelistenable

flutter:

resolution: workspace