name: hyper_secure_storage
description: A starting point for Dart libraries or applications.
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0
  flutter_secure_storage: ">=9.2.0 <10.0.0"
  hyper_storage: ^0.1.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

resolution: workspace