name: hyper_storage_hive
description: A backend for hyper_storage that uses hive_ce for local data storage.

version: 0.1.0

repository: https://github.com/hyper-designed/hyper_storage
homepage: https://github.com/hyper-designed/hyper_storage/tree/main/packages/hyper_storage_hive

environment:
  sdk: ^3.9.0

dependencies:
  hive_ce: ">=2.13.0 <3.0.0"
  hyper_storage: ^0.1.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  path: ^1.9.0

resolution: workspace
