name: hyper_storage
description: A starting point for Dart libraries or applications.
version: 0.1.0

repository: https://github.com/hyper-designed/hyper_storage
homepage: https://github.com/hyper-designed/hyper_storage

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  meta: ">=1.16.0 <2.0.0"

dev_dependencies:
  lints: ^6.0.0
  coverage: ^1.15.0
  test: ^1.26.2

resolution: workspace