name: Code Quality

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**/*.dart'
  pull_request:
    branches:
      - main
    paths:
      - '**/*.dart'

jobs:
  test:
    name: Analyze
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - uses: actions/checkout@v4
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Pub Get
        run: dart pub get

      - name: Check formatting
        run: dart format --set-exit-if-changed .

      - name: Lint
        run: dart analyze . --fatal-infos